version: "3.7"

services:
  web:
    environment:
      - DEBUG=true # any string value is true
    build: .
    command: uvicorn app.app:app --reload --host 0.0.0.0
    volumes:
      - .:/keycloak
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
